name: very_good_cli
description: A Very Good Command Line Interface for Dart
version: 0.0.1-dev.0
homepage: https://github.com/VeryGoodOpenSource/very_good_cli

environment:
  sdk: ">=2.8.1 <3.0.0"

dev_dependencies:
  very_good_analysis: ^1.0.4

executables:
  very_good:
