name: very_good_cli
description: A Very Good Command Line Interface for Dart created by Very Good Ventures.
version: 0.1.0
homepage: https://github.com/VeryGoodOpenSource/very_good_cli

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^1.6.0
  io: ^0.3.4
  mason: ^0.0.1-dev.25
  meta: ^1.2.4
  path: ^1.7.0

dev_dependencies:
  coverage: ^0.13.4
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  build_version: ^2.0.1
  mockito: ^4.0.0
  test: ^1.14.3
  very_good_analysis: ^1.0.4

executables:
  very_good:
