name: very_good_cli
description: A Very Good Command Line Interface for Dart created by Very Good Ventures.
version: 0.7.9
homepage: https://github.com/VeryGoodOpenSource/very_good_cli

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.1.0
  glob: ^2.0.2
  lcov_parser: ^0.1.2
  mason: ">=0.1.0-dev.26 <0.1.0-dev.27"
  mason_logger: ">=0.1.0-dev.13 <0.1.0-dev.14"
  meta: ^1.3.0
  path: ^1.8.0
  pub_updater: ^0.2.1
  pubspec_parse: ^1.2.0
  stack_trace: ^1.10.0
  universal_io: ^2.0.4
  usage: ^4.0.2
  very_good_analysis: ^3.0.0
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.2.0
  test: ^1.17.0

executables:
  very_good:
