name: very_good_cli
description: A Very Good Command-Line Interface for Dart created by Very Good Ventures.
version: 0.26.2
homepage: https://cli.vgv.dev/
repository: https://github.com/VeryGoodOpenSource/very_good_cli
issue_tracker: https://github.com/VeryGoodOpenSource/very_good_cli/issues
documentation: https://cli.vgv.dev/docs/overview
topics: [cli, codegen, test, template, boilerplate]

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  collection: ^1.19.0
  equatable: ^2.0.5
  glob: ^2.1.2
  lcov_parser: ^0.1.2
  mason: ^0.1.0
  mason_logger: ^0.3.0
  meta: ^1.15.0
  package_config: ^2.1.0
  pana: ^0.22.21
  path: ^1.9.0
  pub_updater: ^0.5.0
  pubspec_parse: ^1.3.0
  stack_trace: ^1.11.1
  universal_io: ^2.2.2
  very_good_test_runner: ^0.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

executables:
  very_good:
