name: very_good_cli
description: A Very Good Command-Line Interface for Dart created by Very Good Ventures.
version: 0.15.0
repository: https://github.com/VeryGoodOpenSource/very_good_cli

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.1.0
  cli_completion: ">=0.2.0 <0.4.0"
  collection: ^1.17.1
  glob: ^2.0.2
  lcov_parser: ^0.1.2
  mason: 0.1.0-dev.49
  mason_logger: ^0.2.2
  meta: ^1.3.0
  path: ^1.8.0
  pub_updater: ">=0.3.0 <0.4.0"
  pubspec_parse: ^1.2.0
  stack_trace: ^1.10.0
  universal_io: ^2.0.4
  usage: ^4.0.2
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0

executables:
  very_good:
