name: spdx_license_hooks
description: Hook for generating SPDX license.
version: 0.1.0+1
repository: https://github.com/VeryGoodOpenSource/very_good_cli
issue_tracker: https://github.com/VeryGoodOpenSource/very_good_cli/issues
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  archive: ^4.0.7
  http: ^1.2.1
  mason: ^0.1.0
  meta: ^1.12.0
  path: ^1.9.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.29.0
  very_good_analysis: ^10.2.0
