name: ci

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.10.0
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: |
          dart analyze --fatal-infos --fatal-warnings lib
          dart analyze --fatal-infos --fatal-warnings test

      - name: Verify Build
        run: pub run test --run-skipped -t pull-request-only

      - name: Config Git User
        run: |
          # Config Git User
          git config user.name VGV Bot
          git config user.email vgvbot@users.noreply.github.com

      - name: Run Tests
        run: dart test -x pull-request-only --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
